name: hermes-cpu
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=2.1.2
  - pandas=2.2.3
  - scipy=1.14.1
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - pyyaml=6.0.2
  - tqdm=4.66.5
  - pytorch=2.5.1
  - torchvision=0.20.1
  - cpuonly
  - pip:
      - timm==1.0.11
      - hydra-core==1.3.2
      - rich==13.9.4
      - pytest==8.3.3
      - ruff==0.7.0
